# Generated by Django 3.1.7 on 2021-08-12 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('fpl_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=20)),
                ('long_term', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Gameweek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameweek_id', models.SmallIntegerField(default=0)),
                ('result', models.CharField(blank=True, max_length=1, null=True)),
                ('score', models.CharField(blank=True, max_length=5, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('finished', models.BooleanField(default=False)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='LMS.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='LMS.team')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('chosen_result', models.CharField(choices=[('Home', 'Home'), ('Away', 'Away')], max_length=4)),
                ('gameweek_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.gameweek')),
            ],
        ),
    ]
