# Generated by Django 3.1.7 on 2021-08-10 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gameweek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=20)),
                ('away_team', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=1)),
                ('score', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('chosen_result', models.CharField(choices=[('Home', 'Home'), ('Away', 'Away')], max_length=4)),
                ('gameweek_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.gameweek')),
            ],
        ),
    ]
