# Generated by Django 3.1.7 on 2021-08-12 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='long_term',
            new_name='long_name',
        ),
    ]
