# Generated by Django 3.1.7 on 2021-08-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_auto_20210810_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameweek',
            name='result',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='gameweek',
            name='score',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
